export const southIndianDishes = [
  "Idli",
  "Vada",
  "Masala Dosa",
  "Onion Rava Dosa",
  "Ghee Roast",
  "Podi Idli",
  "Sambar Idli",
  "Kara Paniyaram",
  "Sweet Paniyaram",
  "Medu Vada",
  "Upma",
  "Rava Upma",
  "Pongal",
  "Ven Pongal",
  "Khara Pongal",
  "Curd Rice",
  "Lemon Rice",
  "Tamarind Rice (Puliyodharai)",
  "Tomato Rice",
  "Bisi Bele Bath",
  "Vegetable Kurma",
  "Appam",
  "Idiyappam",
  "Kadala Curry",
  "Poori Masala",
  "Kesari Bath",
  "Rava Kesari",
  "Puttu",
  "Chicken Chettinad",
  "Mutton Sukka",
  "Fish Fry",
  "Nethili Fry",
  "Kothu Parotta",
  "Egg Kothu Parotta",
  "Parotta with Salna",
  "Veg Meals",
  "Non-Veg Meals",
  "Sambar Vada",
  "Rasam Vada",
  "Ghee Pongal",
  "Chole Poori",
  "Chapati Kurma",
  "Kal Dosa",
  "Set Dosa",
  "Mysore Masala Dosa",
  "Kuzhi Paniyaram",
  "Uttapam",
  "Onion Uttapam",
  "Tomato Uttapam",
  "Veg Korma",
  "Kadappa Curry",
  "Mutton Biryani (South Style)",
  "Chicken Biryani (Ambur Style)",
  "Dindigul Thalappakatti Biryani",
  "Chettinad Biryani",
  "Hyderabadi Dum Biryani (South Special)",
  "Idli Fry",
  "Idli Manchurian",
  "Gobi 65",
  "Paneer 65",
  "Chicken 65",
  "Pepper Chicken",
  "Mutton Chukka",
  "South Indian Filter Coffee"
];
